name: Publish Scrypted

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron:  '30 9 * * *'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (scrypted)
        uses: docker/build-push-action@v2
        with:
          build-args: GITHUB_SHA=${{ env.GITHUB_SHA }}
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: |
            koush/scrypted:latest
            ghcr.io/koush/scrypted:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
