name: Publish Scrypted

on:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron:  '30 9 * * *'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "16-bullseye"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: server

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (scrypted)
        uses: docker/build-push-action@v2
        with:
          build-args: BASE=${{ matrix.node }}
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/armhf
          push: true
          tags: |
            koush/scrypted:${{ matrix.node }}
            koush/scrypted:${{ matrix.node }}-${{ steps.package-version.outputs.current-version}}
            ${{ matrix.node == '16-bullseye' && 'koush/scrypted:latest' || '' }}
            ghcr.io/koush/scrypted:${{ matrix.node }}
            ghcr.io/koush/scrypted:${{ matrix.node }}-${{ steps.package-version.outputs.current-version}}
            ${{ matrix.node == '16-bullseye' && 'ghcr.io/koush/scrypted:latest' || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
